Added workflow_dispatch trigger to matrix

diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -1,31 +1,29 @@
 name: matrix-build
 
 on:
-  workflow_dispatch
+  workflow_dispatch:
 
 jobs:
   build-matrix:
-
     strategy:
-        fail-fast: true
-        matrix:
-          python-version: ["3.10","3.11","3.12"] 
-          os: [ubuntu-latest, windows-latest]
-          exclude:
-            - os: windows-latest
-              python-version: 3.11  # This specific combination will be skipped
-    runs-on: ${{ matrix.os }}   
-    steps:  
+      fail-fast: true
+      matrix:
+        python-version: ["3.10", "3.11", "3.12"]
+        os: [ubuntu-latest, windows-latest]
+        exclude:
+          - os: windows-latest
+            python-version: 3.11 # This specific combination will be skipped
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Intentionally fail on windows-latest
+        if: matrix.os == 'windows-latest'
+        run: |
+          echo "Simulation error on windows"
+          exit 1
+      - name: Code checkout from Github
+        uses: actions/checkout@v4
 
-        - name: Intentionally fail on windows-latest
-          if: matrix.os == 'windows-latest'
-          run: |
-            echo "Simulation error on windows"
-            exit 1
-        - name: Code checkout from Github
-          uses: actions/checkout@v4
-
-        - name: setup python ${{ matrix.python-version }}
-          uses: actions/setup-python@v5
-          with:
-            python-version: ${{ matrix.python-version }}
+      - name: setup python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
