fix:if_conditions

diff --git a/.github/workflows/step-config.yaml b/.github/workflows/step-config.yaml
--- a/.github/workflows/step-config.yaml
+++ b/.github/workflows/step-config.yaml
@@ -11,15 +11,17 @@ jobs:
     steps:
       - name: Run when branch is Main
         if: github.ref == 'refs/heads/main' # condition that it should only run when the branch is main
-        continue-on-error: true. # even if this step fails actions should continue to next step
-        run: echo "This is step 1 from main branch"
+        continue-on-error: true # even if this step fails actions should continue to next step
+        run: |
+          echo "This is step 1 from main branch"
+          exit 1
 
-      - name: Run when only previous step is failed
-        #if: always()
-        run: echo "This step runs always"
+      - name: Also run when previous step is failed
+        if: failure()
+        run: echo "Previous step failed so this runs"
 
   Run-on-PE:
-    if: github.event_name == 'push'. # run the job only if it is a pull request
+    if: github.event_name == 'push' # run the job only if it is a pull request
     runs-on: ubuntu-latest
 
     steps:
